# Generated by Django 5.2.6 on 2026-09-12 18:33

import apps.common.fields
import apps.reservations.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='e.g. ["Air conditioned", "Ambient music"]')),
                ('is_premium', models.BooleanField(default=False)),
                ('surcharge', apps.common.fields.MoneyField(help_text='Per-booking surcharge in kobo. 0 for none.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_areas', to='core.branch')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('number', models.CharField(help_text='As written on the table, e.g. 12 or P3.', max_length=10)),
                ('seats_min', models.PositiveSmallIntegerField(default=1, help_text='Below this the table is wasted on the party.', validators=[django.core.validators.MinValueValidator(1)])),
                ('seats_max', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.branch')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='reservations.tablearea')),
            ],
            options={
                'ordering': ['area__display_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.reservations.models.generate_reference, max_length=20, unique=True)),
                ('reserved_for', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=90)),
                ('party_size', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', apps.common.fields.PhoneField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, e.g. +2348012345678.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='confirmed', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Website'), ('phone', 'Phone'), ('walk_in', 'Walk-in')], default='web', max_length=20)),
                ('confirmation_token', models.CharField(default=apps.reservations.models.generate_token, help_text='Lets a guest view or cancel this booking from the emailed link.', max_length=64)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, help_text='Allocated when the booking is made.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.restauranttable')),
                ('area', models.ForeignKey(help_text='What the customer asked for.', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.tablearea')),
            ],
            options={
                'ordering': ['-reserved_for'],
            },
        ),
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('full_day', models.BooleanField(default=True)),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('ends_at', models.TimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='core.branch')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'date'), name='unique_blackout_per_date')],
            },
        ),
        migrations.CreateModel(
            name='ServicePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lunch, Dinner…', max_length=60)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField(help_text='Last seating time, not closing time.')),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)])),
                ('turn_time_minutes', models.PositiveSmallIntegerField(default=90, help_text='How long a table is held for one booking.')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_periods', to='core.branch')),
            ],
            options={
                'ordering': ['weekday', 'starts_at'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'weekday', 'name'), name='unique_service_period'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='service_period_ends_after_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='tablearea',
            constraint=models.UniqueConstraint(fields=('branch', 'slug'), name='unique_area_slug_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('branch', 'number'), name='unique_table_number'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.CheckConstraint(condition=models.Q(('seats_max__gte', models.F('seats_min'))), name='table_seats_max_gte_min'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['branch', 'status', 'reserved_for'], name='reservation_branch__9fbdd0_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['table', 'reserved_for'], name='reservation_table_i_d4a54e_idx'),
        ),
    ]
