# Generated by Django 5.2.6 on 2026-09-12 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Identifier used in code, e.g. order_confirmation. Do not change.', max_length=80, unique=True)),
                ('description', models.CharField(blank=True, help_text='When this email is sent.', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text_body', models.TextField(help_text='Plain-text version. Always sent.')),
                ('html_body', models.TextField(blank=True, help_text='Optional HTML version, sent as an alternative part.')),
                ('available_context', models.JSONField(blank=True, default=list, help_text='Placeholder names available to this template, for reference.')),
                ('is_active', models.BooleanField(default=True, help_text='Turning this off falls back to the built-in wording, not to silence.')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='html_body',
            field=models.TextField(blank=True, help_text='HTML alternative, if any.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, help_text='Plain-text body as sent.'),
        ),
    ]
