# Generated by Django 5.2.6 on 2026-09-11 22:37

import apps.common.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('phone', apps.common.fields.PhoneField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, e.g. +2348012345678.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('whatsapp', apps.common.fields.PhoneField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, e.g. +2348012345678.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('prices_include_vat', models.BooleanField(default=True, help_text='When on, menu prices are what the customer pays and VAT is extracted from them for accounting. When off, VAT is added at checkout. The published terms currently promise tax-inclusive pricing — see docs/PRD.md §7 before changing this.')),
                ('vat_rate_bps', models.PositiveIntegerField(default=750, help_text='Basis points. 750 = 7.5%. Integer, so the rate can never drift.', validators=[django.core.validators.MaxValueValidator(10000)])),
                ('service_charge_bps', models.PositiveIntegerField(default=0, help_text='Basis points applied to the order subtotal. 0 = none.', validators=[django.core.validators.MaxValueValidator(10000)])),
                ('is_accepting_orders', models.BooleanField(default=True, help_text='Manual kill switch. Turn off to stop new orders during a rush.')),
                ('min_order_value', apps.common.fields.MoneyField(help_text='Minimum order subtotal in kobo.')),
                ('free_delivery_threshold', apps.common.fields.MoneyField(blank=True, help_text='Subtotal in kobo at which delivery becomes free. Blank = never.', null=True)),
                ('default_prep_minutes', models.PositiveSmallIntegerField(default=25, help_text='Fallback preparation time when a menu item has none.')),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kuyash Place Restaurant', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('orders_email', models.EmailField(blank=True, max_length=254)),
                ('stat_customers', models.CharField(blank=True, max_length=20)),
                ('stat_dishes', models.CharField(blank=True, max_length=20)),
                ('stat_years', models.CharField(blank=True, max_length=20)),
                ('stat_rating', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='HolidayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('is_closed', models.BooleanField(default=True)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_overrides', to='core.branch')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'date'), name='unique_branch_holiday')],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('service', models.CharField(choices=[('all_day', 'All day'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='all_day', max_length=20)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_closed', models.BooleanField(default=False, help_text='Closed all day for this service.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='core.branch')),
            ],
            options={
                'verbose_name_plural': 'opening hours',
                'ordering': ['weekday', 'opens_at'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'weekday', 'service'), name='unique_branch_weekday_service'), models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='closes_after_opens')],
            },
        ),
    ]
