# Generated by Django 5.2.6 on 2026-09-12 23:04

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='terms, privacy, cookies, refunds, accessibility…')),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown.')),
                ('summary', models.CharField(blank=True, help_text='What changed in this version.', max_length=300)),
                ('effective_from', models.DateField(default=datetime.date.today, help_text='The date this wording takes effect.')),
                ('published', models.BooleanField(default=False, help_text='Unpublished drafts are invisible to customers and to the API.')),
            ],
            options={
                'ordering': ['slug', '-version'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='unique_legal_page_version')],
            },
        ),
    ]
