# Generated by Django 5.2.6 on 2026-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_legal_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_name',
            field=models.CharField(blank=True, help_text='For bank transfer orders. Leave any bank field blank to switch transfer off.', max_length=100),
        ),
    ]
