# Generated by Django 5.2.6 on 2026-09-14 16:47

import apps.gallery.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_bank_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=150)),
                ('awarded_by', models.CharField(max_length=150)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, help_text='Where the award can be verified.')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=120)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.gallery.models.validate_image_size])),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='established_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Shown on the About page. Leave blank to hide it.', null=True),
        ),
    ]
