# Generated by Django 5.2.6 on 2026-09-12 05:20

import apps.carts.models
import apps.common.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_address'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('special_instructions', models.TextField(blank=True)),
                ('unit_price_snapshot', apps.common.fields.MoneyField(help_text='Unit price when the line was last touched. Used to detect price changes.')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['modifier__display_order'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.CharField(db_index=True, default=apps.carts.models.generate_cart_token, help_text='Identifies an anonymous cart. Sent by the client as X-Cart-Token.', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted to an order'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20)),
                ('fulfilment_type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=20)),
                ('tip', apps.common.fields.MoneyField(help_text='Gratuity in kobo. Not subject to VAT.')),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.branch')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='accounts.address')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
