# Generated by Django 5.2.6 on 2026-09-12 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Applied but not yet redeemed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='promotions.promocode'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.menuitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='cartitemmodifier',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='carts.cartitem'),
        ),
        migrations.AddField(
            model_name='cartitemmodifier',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_item_modifiers', to='catalog.modifier'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('user__isnull', False)), fields=('user', 'branch'), name='one_active_cart_per_user_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='cartitemmodifier',
            constraint=models.UniqueConstraint(fields=('cart_item', 'modifier'), name='unique_modifier_per_cart_item'),
        ),
        migrations.AddConstraint(
            model_name='cartitemmodifier',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_modifier_quantity_positive'),
        ),
    ]
