# Generated by Django 5.2.6 on 2026-09-14 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='loyalty_reward',
            field=models.ForeignKey(blank=True, help_text='Applied to the cart; the points are spent when the order is placed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='loyalty.reward'),
        ),
    ]
