# Generated by Django 5.2.6 on 2026-09-12 18:59

import apps.catering.models
import apps.common.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('min_guests', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_guests', models.PositiveIntegerField(default=100)),
                ('price_per_person', apps.common.fields.MoneyField(help_text='Per head in kobo. ₦6,500.00 is 650000.')),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_popular', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catering/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_packages', to='core.branch')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CateringEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.catering.models.generate_reference, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', apps.common.fields.PhoneField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, e.g. +2348012345678.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('guest_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('indicative_total', apps.common.fields.MoneyField(help_text='Guests × per-head price at the time of enquiry. Indicative only.')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Never shown to the customer.')),
                ('quoted_amount', apps.common.fields.MoneyField(blank=True, help_text='The real quote, in kobo.', null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_catering_enquiries', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catering_enquiries', to='core.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catering_enquiries', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catering.cateringpackage')),
            ],
            options={
                'verbose_name_plural': 'catering enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cateringpackage',
            constraint=models.UniqueConstraint(fields=('branch', 'slug'), name='unique_catering_package_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='cateringpackage',
            constraint=models.CheckConstraint(condition=models.Q(('max_guests__gte', models.F('min_guests'))), name='catering_max_guests_gte_min'),
        ),
        migrations.AddIndex(
            model_name='cateringenquiry',
            index=models.Index(fields=['status', 'created_at'], name='catering_ca_status_0296a2_idx'),
        ),
    ]
