# Generated by Django 5.2.6 on 2026-09-13 09:24

import apps.academy.models
import apps.common.fields
import apps.gallery.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_branch_bank_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('masterclass', 'Masterclass')], max_length=20)),
                ('course_type', models.CharField(choices=[('cooking', 'Cooking'), ('baking', 'Baking'), ('plating', 'Plating'), ('business', 'Business'), ('nutrition', 'Nutrition')], max_length=20)),
                ('duration_label', models.CharField(help_text='e.g. "4 weeks".', max_length=60)),
                ('session_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', apps.common.fields.MoneyField(help_text='Course fee in kobo.')),
                ('features', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='academy/courses/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.gallery.models.validate_image_size])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.branch')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('enrolled_count', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Paid seats. Maintained by the enrolment service.')),
                ('schedule_note', models.CharField(blank=True, help_text='e.g. "Saturdays, 10:00–14:00".', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open for enrolment'), ('full', 'Full'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='academy.course')),
            ],
            options={
                'ordering': ['starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.academy.models.generate_reference, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', apps.common.fields.PhoneField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, e.g. +2348012345678.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending_payment', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('transfer', 'Bank transfer')], max_length=20)),
                ('amount', apps.common.fields.MoneyField(help_text='The course fee when the student enrolled, in kobo.')),
                ('amount_paid', apps.common.fields.MoneyField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('hold_expires_at', models.DateTimeField(blank=True, help_text='An unpaid enrolment holds its seat until this moment.', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('guest_token', models.CharField(default=apps.academy.models.generate_guest_token, editable=False, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academy.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academy.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='academy/instructors/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.gallery.models.validate_image_size])),
                ('specialities', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academy.instructor'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='cohort_ends_after_it_starts'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['cohort', 'status'], name='academy_enr_cohort__b8699a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['user', '-created_at'], name='academy_enr_user_id_5fca45_idx'),
        ),
    ]
