# Generated by Django 5.2.6 on 2026-09-12 05:34

import apps.common.fields
import apps.orders.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.orders.models.generate_reference, max_length=20, unique=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', apps.common.fields.PhoneField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, e.g. +2348012345678.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('guest_name', models.CharField(blank=True, max_length=150)),
                ('guest_token', models.CharField(blank=True, default=apps.orders.models.generate_guest_token, help_text='Lets a guest read and cancel this one order. Scoped to it alone.', max_length=64)),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('paid', 'Paid'), ('confirmed', 'Confirmed by the kitchen'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed_delivery', 'Delivery failed'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='pending_payment', max_length=24)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='unpaid', max_length=24)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('transfer', 'Bank transfer'), ('cash', 'Cash on delivery')], max_length=20)),
                ('fulfilment_type', models.CharField(default='delivery', max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_phone', apps.common.fields.PhoneField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, e.g. +2348012345678.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('street', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('delivery_notes', models.TextField(blank=True)),
                ('delivery_zone_name', models.CharField(blank=True, max_length=120)),
                ('subtotal', apps.common.fields.MoneyField()),
                ('discount_total', apps.common.fields.MoneyField()),
                ('delivery_fee', apps.common.fields.MoneyField()),
                ('service_charge', apps.common.fields.MoneyField()),
                ('vat_total', apps.common.fields.MoneyField()),
                ('tip', apps.common.fields.MoneyField()),
                ('grand_total', apps.common.fields.MoneyField()),
                ('amount_paid', apps.common.fields.MoneyField()),
                ('vat_rate_bps', models.PositiveIntegerField(default=750, help_text="The rate at the time of the order, not today's.")),
                ('prices_included_vat', models.BooleanField(default=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('promo_code_snapshot', models.CharField(blank=True, max_length=32)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_ready_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('customer_note', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=150)),
                ('description_snapshot', models.TextField(blank=True)),
                ('variant_name_snapshot', models.CharField(blank=True, max_length=80)),
                ('slug_snapshot', models.SlugField(blank=True, max_length=160)),
                ('image_url_snapshot', models.URLField(blank=True, max_length=500)),
                ('tax_class_snapshot', models.CharField(default='standard', max_length=20)),
                ('unit_price', apps.common.fields.MoneyField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('line_subtotal', apps.common.fields.MoneyField()),
                ('line_discount', apps.common.fields.MoneyField()),
                ('line_vat', apps.common.fields.MoneyField()),
                ('special_instructions', models.TextField(blank=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=120)),
                ('price_delta', apps.common.fields.SignedMoneyField(default=0, help_text='Amount in kobo (₦1.00 = 100). Never enter naira here. May be negative.')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('system', 'System'), ('webhook', 'Webhook')], default='system', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status', '-created_at'], name='orders_orde_branch__3af104_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
    ]
