# Generated by Django 5.2.17 on 2026-09-16 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_loyalty_reward'),
        ('core', '0004_about_content'),
        ('orders', '0002_orderitem_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, help_text="The basket this order was placed from, so confirming payment empties that basket and no other customer's.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='carts.cart'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'placed_at'], name='orders_orde_branch__f5e9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status', 'placed_at'], name='orders_orde_branch__4c478f_idx'),
        ),
    ]
