# Generated by Django 5.2.17 on 2026-09-16 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_loyalty_reward'),
        ('core', '0004_about_content'),
        ('orders', '0003_order_cart_snapshot_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_order_idempotency_key'),
        ),
    ]
