# Generated by Django 5.2.6 on 2026-09-12 05:20

import apps.common.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('is_allergen', models.BooleanField(default=False, help_text='Allergen warnings are shown prominently rather than as a filter chip.')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('emoji', models.CharField(blank=True, help_text='Shown beside the category name.', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.branch')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('base_price', apps.common.fields.MoneyField(help_text='Price in kobo. ₦1,250.00 is 125000.')),
                ('compare_at_price', apps.common.fields.MoneyField(blank=True, help_text="Optional 'was' price for a strike-through. Leave blank for none.", null=True)),
                ('needs_repricing', models.BooleanField(db_index=True, default=True, help_text='ON means the price is an unconfirmed placeholder. Such items are hidden from the public API and block deployment. Turn OFF only once a real naira price has been set.')),
                ('tax_class', models.CharField(choices=[('standard', 'Standard rated'), ('zero_rated', 'Zero rated'), ('exempt', 'Exempt')], default='standard', max_length=20)),
                ('prep_time_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Drives the order ETA. Blank falls back to the branch default.', null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('allergen_note', models.CharField(blank=True, max_length=255)),
                ('is_available_now', models.BooleanField(default=True, help_text="Turn off to '86' an item immediately without unpublishing it.")),
                ('is_featured', models.BooleanField(default=False, help_text="Surfaces in What's Hot.")),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, help_text="When the item first went live. Powers 'sort by newest'.", null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category')),
                ('dietary_tags', models.ManyToManyField(blank=True, related_name='items', to='catalog.dietarytag')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='catalog.menuitem')),
            ],
            options={
                'ordering': ['weekday', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.menuitem')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('min_select', models.PositiveSmallIntegerField(default=0, help_text='0 makes the group optional.')),
                ('max_select', models.PositiveSmallIntegerField(default=1, help_text='1 is a radio, >1 checkboxes.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='catalog.menuitem')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('price_delta', apps.common.fields.SignedMoneyField(default=0, help_text='Added to the line price, in kobo. This is what makes an upgrade cost money.')),
                ('is_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='catalog.modifiergroup')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price_delta', apps.common.fields.SignedMoneyField(default=0, help_text='Added to the base price, in kobo. May be negative for a smaller portion.')),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.menuitem')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('branch', 'slug'), name='unique_category_slug_per_branch'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'category', 'is_active', 'display_order'], name='catalog_men_branch__05ddce_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'is_featured'], name='catalog_men_branch__1809c0_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'needs_repricing'], name='catalog_men_branch__d05e15_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('branch', 'slug'), name='unique_item_slug_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='availabilitywindow',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='availability_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='availabilitywindow',
            constraint=models.UniqueConstraint(fields=('item', 'weekday', 'starts_at'), name='unique_item_window'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('max_select__gte', models.F('min_select'))), name='max_select_gte_min_select'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('max_select__gte', 1)), name='max_select_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='modifier',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_modifier_per_group'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('item', 'name'), name='unique_variant_per_item'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('item',), name='one_default_variant_per_item'),
        ),
    ]
