# Generated by Django 5.2.17 on 2026-09-16 09:20

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
