# Generated by Django 5.2.6 on 2026-09-12 05:20

import apps.common.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage off'), ('fixed', 'Fixed amount off'), ('free_delivery', 'Free delivery')], max_length=20)),
                ('value', models.PositiveIntegerField(default=0, help_text='For a percentage: basis points (1000 = 10%). For a fixed amount: kobo. Ignored for free delivery.', validators=[django.core.validators.MaxValueValidator(10000)])),
                ('min_order_value', apps.common.fields.MoneyField(help_text='Minimum subtotal in kobo for the code to apply.')),
                ('max_discount', apps.common.fields.MoneyField(blank=True, help_text='Caps a percentage discount, in kobo. Blank = uncapped.', null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total redemptions allowed across all customers.', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='Redemptions allowed per customer.', null=True)),
                ('first_order_only', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this code may ever be listed to customers. Default off: the current frontend enumerates every available code to the user.')),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Leave empty to apply to the whole order.', related_name='promo_codes', to='catalog.category')),
                ('applicable_items', models.ManyToManyField(blank=True, help_text='Leave empty to apply to the whole order.', related_name='promo_codes', to='catalog.menuitem')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='core.branch')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_reference', models.CharField(blank=True, db_index=True, help_text='Opaque order reference. Becomes a foreign key in Phase 1D.', max_length=20)),
                ('discount_amount', apps.common.fields.MoneyField(help_text='Discount granted, in kobo.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.promocode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='unique_promo_code_per_branch'),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['promo_code', 'status'], name='promotions__promo_c_a2597b_idx'),
        ),
    ]
