# Generated by Django 5.2.6 on 2026-09-12 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoredemption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promo_redemptions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='promoredemption',
            name='order_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Denormalised order reference, kept so support lookups stay cheap.', max_length=20),
        ),
    ]
