# Generated by Django 5.2.6 on 2026-09-12 05:20

import apps.common.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('fee', apps.common.fields.MoneyField(help_text='Flat delivery fee in kobo. ₦1,500.00 is 150000.')),
                ('min_order_value', apps.common.fields.MoneyField(help_text='Minimum order subtotal for this zone, in kobo.')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=40, help_text='Typical door-to-door time. Feeds the order ETA.')),
                ('areas', models.JSONField(blank=True, default=list, help_text='Area or district names matched against a customer\'s address, e.g. ["Victoria Island", "VI", "Eko Atlantic"]. Case-insensitive.')),
                ('polygon', models.TextField(blank=True, help_text='Reserved for GeoJSON boundary matching (Phase 3). Not used yet.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='core.branch')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'slug'), name='unique_zone_slug_per_branch')],
            },
        ),
    ]
