# Generated by Django 5.2.17 on 2026-09-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryassignment_order_riderprofile_current_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='areas',
            field=models.JSONField(blank=True, default=list, help_text='Area or district names matched against a customer\'s address, e.g. ["Victoria Island", "VI", "Eko Atlantic"]. Case-insensitive. Saving mirrors this list into the indexed DeliveryArea table that address matching actually queries.'),
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='As staff typed it.', max_length=120)),
                ('normalised', models.CharField(help_text='Lower-cased, punctuation folded to spaces. Matched against.', max_length=120)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_rows', to='delivery.deliveryzone')),
            ],
            options={
                'ordering': ['normalised'],
                'indexes': [models.Index(fields=['normalised'], name='delivery_de_normali_c761d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('zone', 'normalised'), name='unique_area_per_zone')],
            },
        ),
    ]
