# Generated by Django 5.2.6 on 2026-09-12 05:20

import apps.common.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=10)),
                ('recipient_name', models.CharField(max_length=150)),
                ('phone', apps.common.fields.PhoneField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, e.g. +2348012345678.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('street', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, help_text='District or neighbourhood, e.g. Victoria Island. Used to resolve the zone.', max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('delivery_notes', models.TextField(blank=True)),
                ('zone_overridden', models.BooleanField(default=False, help_text='Set when staff pick the zone by hand; automatic resolution then leaves it alone.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
