# Generated by Django 5.2.6 on 2026-09-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Resolved automatically on save. Blank means outside the delivery area.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='delivery.deliveryzone'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_address_per_user'),
        ),
    ]
