# Generated by Django 5.2.6 on 2026-09-14 16:29

import apps.common.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_wishlistitem'),
        ('core', '0003_branch_bank_transfer'),
        ('orders', '0002_orderitem_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('min_points', models.PositiveIntegerField(help_text='Lifetime points needed to reach this tier.', unique=True)),
                ('points_multiplier_bps', models.PositiveIntegerField(default=10000, help_text='Basis points. 10000 = 1× the base earn rate, 15000 = 1.5×.', validators=[django.core.validators.MinValueValidator(1)])),
                ('birthday_points', models.PositiveIntegerField(default=0, help_text="Points granted on the member's birthday. 0 = none.")),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Extra perks, one per line. Only list what the restaurant actually honours.')),
                ('colour', models.CharField(default='#94a3b8', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a hex colour such as #eab308.')])),
            ],
            options={
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_balance', models.IntegerField(default=0, help_text='Cached sum of the ledger. Can go negative after a reversal.')),
                ('lifetime_points', models.IntegerField(default=0, help_text='Points earned, net of reversed earnings. Decides the tier.')),
                ('is_closed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='loyalty.loyaltytier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('points_cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reward_type', models.CharField(choices=[('discount', 'Money off'), ('free_delivery', 'Free delivery'), ('free_item', 'Free dish')], max_length=20)),
                ('value', apps.common.fields.MoneyField(help_text='Kobo off the order. Money-off rewards only.')),
                ('min_order_value', apps.common.fields.MoneyField(help_text='Subtotal in kobo needed to use it. 0 = none.')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='How many can still be redeemed. Blank = unlimited.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.branch')),
                ('menu_item', models.ForeignKey(blank=True, help_text='Free-dish rewards only: one of these comes off the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='catalog.menuitem')),
            ],
            options={
                'ordering': ['display_order', 'points_cost'],
            },
        ),
        migrations.CreateModel(
            name='PointsLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('expire', 'Expired'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], db_index=True, max_length=20)),
                ('points', models.IntegerField(help_text='Signed. Negative for redemptions, expiry and reversals of earnings.')),
                ('description', models.CharField(max_length=200)),
                ('idempotency_key', models.CharField(blank=True, help_text='Stops the same event (an order, a birthday) posting twice.', max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='loyalty.loyaltyaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to='orders.order')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='loyalty.pointsledgerentry')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='loyalty.reward')),
            ],
            options={
                'verbose_name_plural': 'points ledger entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_spent', models.PositiveIntegerField()),
                ('discount_amount', apps.common.fields.MoneyField()),
                ('status', models.CharField(choices=[('spent', 'Spent on an order'), ('reversed', 'Points returned')], default='spent', max_length=20)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.loyaltyaccount')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_redemption', to='orders.order')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.reward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
