# Generated by Django 5.2.17 on 2026-09-16 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        ('orders', '0003_order_cart_snapshot_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pointsledgerentry',
            index=models.Index(fields=['account', '-created_at'], name='loyalty_poi_account_3bb1f9_idx'),
        ),
    ]
