# Generated by Django 5.2.6 on 2026-09-13 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('orders', '0002_orderitem_public_id'),
        ('payments', '0002_paymenttransaction_save_method_savedpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='enrolment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='academy.enrolment'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('enrolment__isnull', True), ('order__isnull', False)), models.Q(('enrolment__isnull', False), ('order__isnull', True)), _connector='OR'), name='transaction_pays_for_exactly_one_thing'),
        ),
    ]
