# Generated by Django 5.2.17 on 2026-09-16 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('orders', '0003_order_cart_snapshot_and_indexes'),
        ('payments', '0003_paymenttransaction_enrolment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Caller-supplied key for payments recorded by staff. Unique per payable, so a double-clicked “transfer received” cannot be banked twice.', max_length=64),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Money settled in a way a person must look at — a second charge on an already-paid order, or a seat that no longer exists. Never set by a customer.'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='review_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text="Caller-supplied key. Unique per order, so two managers double-clicking Refund cannot send the customer's money back twice.", max_length=64),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1, help_text='Deliveries that collapsed onto this row — an attack shows up here as a count.'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('order', 'idempotency_key'), name='unique_manual_payment_per_order_key'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('order', 'idempotency_key'), name='unique_refund_per_order_key'),
        ),
    ]
